=== NCIP/catrip/catrip/codebase/projects/gui/conf/simplegui/simpleQueryInterface-config.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--W3C Schema generated by XMLSPY v5 U (http://www.xmlspy.com)-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
	<xs:complexType name="inServicePathTreeType">
		<xs:sequence>
			<xs:element name="Association" type="subNodeType" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="depth" type="xs:string" use="optional"/>
	</xs:complexType>
	<xs:complexType name="foreignAssociationInboundTree">
		<xs:sequence>
			<xs:element name="foreignAssociationInboundPath" type="objectElementType" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="linkNodeType">
		<xs:sequence>
			<xs:element name="Association" type="linkNodeType" minOccurs="0"/>
		</xs:sequence>
		<xs:attribute name="childCount" type="xs:string" use="optional"/>
		<xs:attribute name="className" type="xs:string" use="required"/>
		<xs:attribute name="roleName" type="xs:string" use="optional"/>
	</xs:complexType>
	<xs:complexType name="objectElementType">
		<xs:sequence>
			<xs:element name="Association" type="linkNodeType"/>
		</xs:sequence>
		<xs:attribute name="className" type="xs:string" use="required"/>
		<xs:attribute name="refID" type="xs:string" use="required"/>
		<xs:attribute name="depth" type="xs:string" use="optional"/>
		<xs:attribute name="cdeName" type="xs:string" use="required"/>
		<xs:attribute name="displaybleAttributes" type="xs:string" use="required"/>
		<xs:attribute name="display" type="xs:string" use="required"/>
	</xs:complexType>
	<xs:complexType name="outboundpathType">
		<xs:sequence>
			<xs:element name="Association" type="linkNodeType"/>
		</xs:sequence>
		<xs:attribute name="depth" type="xs:string" use="optional"/>
		<xs:attribute name="cdeName" type="xs:string" use="required"/>
	</xs:complexType>
	<xs:complexType name="serviceType">
		<xs:sequence>
			<xs:element name="targets" type="targetsType"/>
			<xs:element name="foreignAssociationInboundTree" type="foreignAssociationInboundTree"/>
		</xs:sequence>
		<xs:attribute name="displayName" type="xs:string" use="required"/>
		<xs:attribute name="url" type="xs:string" use="required"/>
		<xs:attribute name="metadataXml" type="xs:string" use="required"/>
	</xs:complexType>
	<xs:element name="simpleGuiServices">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="service" type="serviceType" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="subNodeType">
		<xs:sequence>
			<xs:element name="Association" type="subNodeType" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="childCount" type="xs:int" use="optional"/>
		<xs:attribute name="className" type="xs:string" use="required"/>
		<xs:attribute name="refID" type="xs:string" use="required"/>
		<xs:attribute name="roleName" type="xs:string" use="required"/>
		<xs:attribute name="displaybleAttributes" type="xs:string" use="optional"/>
		<xs:attribute name="display" type="xs:boolean" use="required"/>
	</xs:complexType>
	<xs:complexType name="targetElementType">
		<xs:sequence>
			<xs:element name="associatedObjectTree" type="inServicePathTreeType"/>
			<xs:element name="foreignAssociationOutboundPath" type="outboundpathType"/>
		</xs:sequence>
		<xs:attribute name="className" type="xs:string" use="required"/>
		<xs:attribute name="refID" type="xs:string" use="required"/>
		<xs:attribute name="displaybleAttributes" type="xs:string" use="required"/>
		<xs:attribute name="display" type="xs:string" use="required"/>
	</xs:complexType>
	<xs:complexType name="targetsType">
		<xs:sequence>
			<xs:element name="objectElement" type="targetElementType" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
</xs:schema>

=== NCIP/catrip/catrip/codebase/projects/gui/backup/conf/simplegui/SimpleGuiObjectGraph-CGEMS.xml
<?xml version="1.0" encoding="UTF-8"?>
<simpleGuiServices xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="simpleQueryInterface-config.xsd">
	<service displayName="CGEMS" url="http://catrip1.duhs.duke.edu:8080/wsrf_cgems/services/cagrid/CGEMS" metadataXml="CaTRIPCGEMS_domainModel.xml" impls="false">
		<targets>
			<objectElement className="gov.nih.nci.caintegrator.domain.study.bean.StudyParticipant" 
							displaybleAttributes="administrativeGenderCode,caseControlStatus,daysOffStudy,daysOnStudy,ethnicGroupCode,familyHistory,institutionName,isOffStudy,raceCode" display="true">
				<associatedObjectTree>
					<Association className="gov.nih.nci.caintegrator.domain.analysis.snp.bean.SNPAnalysisGroup" 
								displaybleAttributes="name,description,methods"  roleName="analysisGroupCollection" display="true">
						<Association className="gov.nih.nci.caintegrator.domain.analysis.snp.bean.SNPAssociationAnalysis" 
								displaybleAttributes="neoplasmPresent,extentInvolvement,otherExtentInvolvement" roleName="snpAssociationAnalysis" display="true">
								<Association className="gov.nih.nci.caintegrator.domain.analysis.snp.bean.SNPAssociationFinding"
									 displaybleAttributes="pvalue,rank" roleName="snpAssociationFindingCollection" display="true"/>
						</Association>
					</Association>
				</associatedObjectTree>
				<foreignAssociationOutboundPath cdeName="studySubjectIdentifier"/>
			</objectElement>
		</targets>
		
		
		<foreignAssociationInboundTree>

			<foreignAssociationInboundPath className="gov.nih.nci.caintegrator.domain.analysis.snp.bean.SNPAnalysisGroup" 
										 cdeName="studySubjectIdentifier" displaybleAttributes="name,description,memberCount" display="true">
				<Association className="gov.nih.nci.caintegrator.domain.study.bean.StudyParticipant">
					<Association className="gov.nih.nci.caintegrator.domain.analysis.snp.bean.SNPAnalysisGroup" roleName="analysisGroupCollection"/>
				</Association>
			</foreignAssociationInboundPath>
			
			<foreignAssociationInboundPath className="gov.nih.nci.caintegrator.domain.analysis.snp.bean.SNPAssociationAnalysis" 
										 cdeName="studySubjectIdentifier" displaybleAttributes="name,description,methods" display="true">
				<Association className="gov.nih.nci.caintegrator.domain.study.bean.StudyParticipant">
					<Association className="gov.nih.nci.caintegrator.domain.analysis.snp.bean.SNPAnalysisGroup" roleName="analysisGroupCollection">
						<Association className="gov.nih.nci.caintegrator.domain.analysis.snp.bean.SNPAssociationAnalysis" roleName="snpAssociationAnalysis"/>
				      </Association>
				</Association>
			</foreignAssociationInboundPath>

			<foreignAssociationInboundPath className="gov.nih.nci.caintegrator.domain.analysis.snp.bean.SNPAssociationFinding" 
										 cdeName="studySubjectIdentifier" displaybleAttributes="pvalue,rank" display="true">
				<Association className="gov.nih.nci.caintegrator.domain.study.bean.StudyParticipant">
					<Association className="gov.nih.nci.caintegrator.domain.analysis.snp.bean.SNPAnalysisGroup" roleName="analysisGroupCollection">
						<Association className="gov.nih.nci.caintegrator.domain.analysis.snp.bean.SNPAssociationAnalysis" roleName="snpAssociationAnalysis">
							<Association className="gov.nih.nci.caintegrator.domain.analysis.snp.bean.SNPAssociationFinding" roleName="snpAssociationFindingCollection"/>
						</Association>							
				      </Association>
				</Association>
			</foreignAssociationInboundPath>

			<foreignAssociationInboundPath className="gov.nih.nci.caintegrator.domain.annotation.snp.bean.SNPPanel" 
										 cdeName="studySubjectIdentifier" displaybleAttributes="assayCount,description,name,technology,vendor" display="true">
				<Association className="gov.nih.nci.caintegrator.domain.study.bean.StudyParticipant">
					<Association className="gov.nih.nci.caintegrator.domain.study.bean.Study" roleName="study">	
						<Association className="gov.nih.nci.caintegrator.domain.annotation.snp.bean.SNPPanel" roleName="snpPanelCollection"/>
					</Association>
				</Association>
			</foreignAssociationInboundPath>

			<foreignAssociationInboundPath className="gov.nih.nci.caintegrator.domain.annotation.snp.bean.SNPAssay" 
										 cdeName="studySubjectIdentifier" displaybleAttributes="designAlleles,designScore,designSequence,designStrand,status" display="true">
				<Association className="gov.nih.nci.caintegrator.domain.study.bean.StudyParticipant">
					<Association className="gov.nih.nci.caintegrator.domain.study.bean.Study" roleName="study">	
						<Association className="gov.nih.nci.caintegrator.domain.annotation.snp.bean.SNPPanel" roleName="snpPanelCollection">
							<Association className="gov.nih.nci.caintegrator.domain.annotation.snp.bean.SNPAssay" roleName="snpAssayCollection"/>
						</Association>
					</Association>
				</Association>
			</foreignAssociationInboundPath>

			<foreignAssociationInboundPath className="gov.nih.nci.caintegrator.domain.annotation.snp.bean.SNPAnnotation" 
										 cdeName="studySubjectIdentifier" 
										 displaybleAttributes="chromosomeLocation,chromosomeName,dbsnpBuild,geneLocation,genomeBuild,referenceSequence,referenceStrand" display="true">
				<Association className="gov.nih.nci.caintegrator.domain.study.bean.StudyParticipant">
					<Association className="gov.nih.nci.caintegrator.domain.study.bean.Study" roleName="study">	
						<Association className="gov.nih.nci.caintegrator.domain.annotation.snp.bean.SNPPanel" roleName="snpPanelCollection">
							<Association className="gov.nih.nci.caintegrator.domain.annotation.snp.bean.SNPAssay" roleName="snpAssayCollection">
								<Association className="gov.nih.nci.caintegrator.domain.annotation.snp.bean.SNPAnnotation" roleName="snpAnnotation"/>
							</Association>
						</Association>
					</Association>
				</Association>
			</foreignAssociationInboundPath>
															
		</foreignAssociationInboundTree>
	</service>
</simpleGuiServices>

=== NCIP/catrip/codebase/antfiles/demo/REMOTE-SimpleGuiObjectGraph.xml
<?xml version="1.0" encoding="UTF-8"?>

<!--L
  Copyright Duke Comprehensive Cancer Center

  Distributed under the OSI-approved BSD 3-Clause License.
  See http://ncip.github.com/catrip/LICENSE.txt for details.
L-->

<simpleGuiServices xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="simpleQueryInterface-config.xsd">
	<service displayName="caTissueCore" url="http://catrip1.duhs.duke.edu:8080/wsrf/services/cagrid/CaTissueCore_Full" metadataXml="caTissueCore_domainModel.xml" impls="true">
		<targets>
			<objectElement className="edu.wustl.catissuecore.domainobject.impl.TissueSpecimenImpl" refID="18785753-F2FC-3542-E044-0003BA4529A9" displaybleAttributes="type,available,positionDimensionOne,positionDimensionTwo,barcode,activityStatus,quantityInGram,availableQuantityInGram" display="true">
				<associatedObjectTree>
					<Association className="edu.wustl.catissuecore.domainobject.impl.SpecimenCollectionGroupImpl" displaybleAttributes="clinicalDiagnosis,clinicalStatus,activityStatus" refID="18785753-F2E4-3542-E044-0003BA4529A9" roleName="specimenCollectionGroup" display="true">
						<Association className="edu.wustl.catissuecore.domainobject.impl.ClinicalReportImpl" displaybleAttributes="surgicalPathologyNumber" refID="18785753-F306-3542-E044-0003BA4529A9" roleName="clinicalReport" display="true">
							<Association className="edu.wustl.catissuecore.domainobject.impl.ParticipantMedicalIdentifierImpl" displaybleAttributes="id" refID="18785753-F302-3542-E044-0003BA4529A9" roleName="participantMedicalIdentifier" display="false"/>
						</Association>
					</Association>
					<Association className="edu.wustl.catissuecore.domainobject.impl.SpecimenCharacteristicsImpl" displaybleAttributes="tissueSite,tissueSide,pathologicalStatus" refID="18785753-F312-3542-E044-0003BA4529A9" roleName="specimenCharacteristics" display="true"/>
				</associatedObjectTree>
				<foreignAssociationOutboundPath cdeName="medicalRecordNumber">
					<Association className="edu.wustl.catissuecore.domainobject.impl.SpecimenCollectionGroupImpl" roleName="specimenCollectionGroup">
						<Association className="edu.wustl.catissuecore.domainobject.impl.ClinicalReportImpl" roleName="clinicalReport">
							<Association className="edu.wustl.catissuecore.domainobject.impl.ParticipantMedicalIdentifierImpl" roleName="participantMedicalIdentifier"/>
						</Association>
					</Association>
				</foreignAssociationOutboundPath>
			</objectElement>
			<objectElement className="edu.wustl.catissuecore.domainobject.impl.CellSpecimenImpl" refID="18785753-F315-3542-E044-0003BA4529A9" displaybleAttributes="barcode,activityStatus,type,quantityInCellCount,positionDimensionOne,positionDimensionTwo,available,availableQuantityInCellCount" display="true">
				<associatedObjectTree>
					<Association className="edu.wustl.catissuecore.domainobject.impl.SpecimenCollectionGroupImpl" displaybleAttributes="clinicalDiagnosis,clinicalStatus,activityStatus" refID="18785753-F2E4-3542-E044-0003BA4529A9" roleName="specimenCollectionGroup" display="true">
						<Association className="edu.wustl.catissuecore.domainobject.impl.ClinicalReportImpl" displaybleAttributes="surgicalPathologyNumber" refID="18785753-F306-3542-E044-0003BA4529A9" roleName="clinicalReport" display="true"/>
					</Association>
				</associatedObjectTree>
				<foreignAssociationOutboundPath cdeName="medicalRecordNumber">
					<Association className="edu.wustl.catissuecore.domainobject.impl.SpecimenCollectionGroupImpl" roleName="specimenCollectionGroup">
						<Association className="edu.wustl.catissuecore.domainobject.impl.ClinicalReportImpl" roleName="clinicalReport">
							<Association className="edu.wustl.catissuecore.domainobject.impl.ParticipantMedicalIdentifierImpl" roleName="participantMedicalIdentifier"/>
						</Association>
					</Association>
				</foreignAssociationOutboundPath>
			</objectElement>
		</targets>
		<foreignAssociationInboundTree>
			<foreignAssociationInboundPath className="edu.wustl.catissuecore.domainobject.impl.ParticipantImpl" refID="18785753-F2E3-3542-E044-0003BA4529A9" cdeName="medicalRecordNumber" displaybleAttributes="sexGenotype,gender,race,ethnicity,activityStatus" display="true">
				<Association className="edu.wustl.catissuecore.domainobject.impl.ParticipantMedicalIdentifierImpl">
					<Association className="edu.wustl.catissuecore.domainobject.impl.ParticipantImpl" roleName="participant"/>
				</Association>
			</foreignAssociationInboundPath>
		</foreignAssociationInboundTree>
	</service>
	<service displayName="caTissueCAE" url="http://catrip1.duhs.duke.edu:8080/wsrf_cae/services/cagrid/CAE" metadataXml="CaTRIPcaTissueCAE_domainModel.xml" impls="false">
		<targets>
			<objectElement className="edu.duke.catrip.cae.domain.general.Participant" refID="Participant" displaybleAttributes="gender,race,ethnicity" display="true">
				<associatedObjectTree>
					<Association className="edu.duke.catrip.cae.domain.general.ParticipantMedicalIdentifier" refID="ParticipantMedicalIdentifier" roleName="medicalRecordNumberCollection" display="false"/>
					<Association className="edu.pitt.cabig.cae.domain.general.AnnotationEventParameters" refID="AnnotationEventParameters" roleName="annotationEventParameters" display="false">
						<Association className="edu.pitt.cabig.cae.domain.breast.BreastPositiveSurgicalMargin" displaybleAttributes="neoplasmPresent,extentInvolvement,otherExtentInvolvement" refID="BreastPositiveSurgicalMargin" roleName="annotationSetCollection" display="true"/>
						<Association className="edu.pitt.cabig.cae.domain.general.ThreeDimensionalSize" displaybleAttributes="greatestDimension,additionalDimensionY,additionalDimensionZ" refID="ThreeDimensionalSize" roleName="annotationSetCollection" display="true"/>
					</Association>
				</associatedObjectTree>
				<foreignAssociationOutboundPath cdeName="medicalRecordNumber">
					<Association className="edu.duke.catrip.cae.domain.general.ParticipantMedicalIdentifier" roleName="medicalRecordNumberCollection"/>
				</foreignAssociationOutboundPath>
			</objectElement>
		</targets>
		<foreignAssociationInboundTree>
			<foreignAssociationInboundPath className="edu.pitt.cabig.cae.domain.breast.NottinghamHistopathologicGrade" refID="NottinghamHistopathologicGrade" cdeName="medicalRecordNumber" displaybleAttributes="tubuleFormation,nuclearPleomorphism,totalScore,totalScoreMVR" display="true">
				<Association className="edu.duke.catrip.cae.domain.general.ParticipantMedicalIdentifier">
					<Association className="edu.duke.catrip.cae.domain.general.Participant" roleName="participant">
						<Association className="edu.pitt.cabig.cae.domain.general.AnnotationEventParameters" roleName="annotationEventParametersCollection">
							<Association className="edu.pitt.cabig.cae.domain.breast.NottinghamHistopathologicGrade" roleName="annotationSetCollection"/>
						</Association>
					</Association>
				</Association>
			</foreignAssociationInboundPath>
			<foreignAssociationInboundPath className="edu.pitt.cabig.cae.domain.general.ThreeDimensionalSize" refID="ThreeDimensionalSize" cdeName="medicalRecordNumber" displaybleAttributes="greatestDimension,additionalDimensionY,additionalDimensionZ" display="true">
				<Association className="edu.duke.catrip.cae.domain.general.ParticipantMedicalIdentifier">
					<Association className="edu.duke.catrip.cae.domain.general.Participant" roleName="participant">
						<Association className="edu.pitt.cabig.cae.domain.general.AnnotationEventParameters" roleName="annotationEventParametersCollection">
							<Association className="edu.pitt.cabig.cae.domain.general.ThreeDimensionalSize" roleName="annotationSetCollection"/>
						</Association>
					</Association>
				</Association>
			</foreignAssociationInboundPath>
		</foreignAssociationInboundTree>
	</service>
</simpleGuiServices>

=== NCIP/catrip/catrip/codebase/projects/gui/backup/conf-10.04/simplegui/SimpleGuiObjectGraph.xml
<?xml version="1.0" encoding="UTF-8"?>
<simpleGuiServices xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="simpleQueryInterface-config.xsd">
	
	
	<service displayName="Tissue Bank" url="http://localhost:8080/wsrf/services/cagrid/CaTissueCore_Full" metadataXml="_SimpleGUI_caTissueCore_domainModel.xml" impls="true">
		<targets>
			<objectElement className="edu.wustl.catissuecore.domainobject.impl.TissueSpecimenImpl"   displaybleAttributes="type,available,positionDimensionOne,positionDimensionTwo,barcode,activityStatus,quantityInGram,availableQuantityInGram" display="true">
				<associatedObjectTree>
					<Association className="edu.wustl.catissuecore.domainobject.impl.SpecimenCollectionGroupImpl" displaybleAttributes="clinicalDiagnosis,clinicalStatus,activityStatus"   roleName="specimenCollectionGroup" display="true">
						<Association className="edu.wustl.catissuecore.domainobject.impl.ClinicalReportImpl" displaybleAttributes="surgicalPathologyNumber"   roleName="clinicalReport" display="true">
							<Association className="edu.wustl.catissuecore.domainobject.impl.ParticipantMedicalIdentifierImpl" displaybleAttributes="id"   roleName="participantMedicalIdentifier" display="false"/>
						</Association>
					</Association>
					<Association className="edu.wustl.catissuecore.domainobject.impl.SpecimenCharacteristicsImpl" displaybleAttributes="tissueSite,tissueSide,pathologicalStatus"   roleName="specimenCharacteristics" display="true"/>
				</associatedObjectTree>
				<foreignAssociationOutboundPath cdeName="medicalRecordNumber">
					<Association className="edu.wustl.catissuecore.domainobject.impl.SpecimenCollectionGroupImpl" roleName="specimenCollectionGroup">
						<Association className="edu.wustl.catissuecore.domainobject.impl.ClinicalReportImpl" roleName="clinicalReport">
							<Association className="edu.wustl.catissuecore.domainobject.impl.ParticipantMedicalIdentifierImpl" roleName="participantMedicalIdentifier"/>
						</Association>
					</Association>
				</foreignAssociationOutboundPath>
			</objectElement>
			<objectElement className="edu.wustl.catissuecore.domainobject.impl.CellSpecimenImpl"   displaybleAttributes="barcode,activityStatus,type,quantityInCellCount,positionDimensionOne,positionDimensionTwo,available,availableQuantityInCellCount" display="true">
				<associatedObjectTree>
					<Association className="edu.wustl.catissuecore.domainobject.impl.SpecimenCollectionGroupImpl" displaybleAttributes="clinicalDiagnosis,clinicalStatus,activityStatus"   roleName="specimenCollectionGroup" display="true">
						<Association className="edu.wustl.catissuecore.domainobject.impl.ClinicalReportImpl" displaybleAttributes="surgicalPathologyNumber"   roleName="clinicalReport" display="true"/>
					</Association>
				</associatedObjectTree>
				<foreignAssociationOutboundPath cdeName="medicalRecordNumber">
					<Association className="edu.wustl.catissuecore.domainobject.impl.SpecimenCollectionGroupImpl" roleName="specimenCollectionGroup">
						<Association className="edu.wustl.catissuecore.domainobject.impl.ClinicalReportImpl" roleName="clinicalReport">
							<Association className="edu.wustl.catissuecore.domainobject.impl.ParticipantMedicalIdentifierImpl" roleName="participantMedicalIdentifier"/>
						</Association>
					</Association>
				</foreignAssociationOutboundPath>
			</objectElement>
		</targets>
		<foreignAssociationInboundTree>
			<foreignAssociationInboundPath className="edu.wustl.catissuecore.domainobject.impl.ParticipantImpl"   cdeName="medicalRecordNumber" displaybleAttributes="sexGenotype,gender,race,ethnicity,activityStatus" display="true">
				<Association className="edu.wustl.catissuecore.domainobject.impl.ParticipantMedicalIdentifierImpl">
					<Association className="edu.wustl.catissuecore.domainobject.impl.ParticipantImpl" roleName="participant"/>
				</Association>
			</foreignAssociationInboundPath>
		</foreignAssociationInboundTree>
	</service>
	

	
	<service displayName="Clinical Annotation Engine" url="http://localhost:8080/wsrf_cae/services/cagrid/CAE" metadataXml="_SimpleGUI_CAE_domainModel.xml" impls="false">
		<targets>
			<objectElement className="edu.duke.catrip.cae.domain.general.Participant"   displaybleAttributes="gender,race,ethnicity" display="true">
				<associatedObjectTree>
					<Association className="edu.duke.catrip.cae.domain.general.ParticipantMedicalIdentifier"   roleName="medicalRecordNumberCollection" display="false"/>
					<Association className="edu.duke.catrip.cae.domain.general.Accession"   roleName="accession" display="false">
						<Association className="edu.duke.catrip.cae.domain.general.Specimen"   roleName="specimen" display="false">
							<Association className="edu.pitt.cabig.cae.domain.general.AnnotationEventParameters"   roleName="annotationEventParameters" display="false">
								<Association className="edu.pitt.cabig.cae.domain.general.ThreeDimensionalTumorSize" displaybleAttributes="greatestDimension,MVR"   roleName="annotationSetCollection" display="true"/>
								<Association className="edu.pitt.cabig.cae.domain.breast.BreastSpecimenCharacteristics" displaybleAttributes="lymphNodeSamplingProcedure,laterality,lateralityMVR"   roleName="annotationSetCollection" display="true"/>
 								<Association className="edu.pitt.cabig.cae.domain.breast.BreastCancerBiomarkers" displaybleAttributes="estrogenReceptor,progesteroneReceptor,HER2Status,HER2TestType,EGFRStatus"   roleName="annotationSetCollection" display="true"/>
 								<Association className="edu.pitt.cabig.cae.domain.breast.NottinghamHistopathologicGrade" displaybleAttributes="tubuleFormation,nuclearPleomorphism,totalScore,totalScoreMVR"   roleName="annotationSetCollection" display="true"/>
							</Association>
						</Association>
					</Association>
				</associatedObjectTree>
				<foreignAssociationOutboundPath cdeName="medicalRecordNumber">
					<Association className="edu.duke.catrip.cae.domain.general.ParticipantMedicalIdentifier" roleName="medicalRecordNumberCollection"/>
				</foreignAssociationOutboundPath>
			</objectElement>
		</targets>

		<foreignAssociationInboundTree>
			<foreignAssociationInboundPath className="edu.pitt.cabig.cae.domain.breast.NottinghamHistopathologicGrade"   cdeName="medicalRecordNumber" displaybleAttributes="tubuleFormation,nuclearPleomorphism,totalScore,totalScoreMVR" display="true">
				<Association className="edu.duke.catrip.cae.domain.general.ParticipantMedicalIdentifier">
					<Association className="edu.duke.catrip.cae.domain.general.Participant" roleName="participant">
						<Association className="edu.pitt.cabig.cae.domain.general.AnnotationEventParameters" roleName="annotationEventParametersCollection">
							<Association className="edu.pitt.cabig.cae.domain.breast.NottinghamHistopathologicGrade" roleName="annotationSetCollection"/>
						</Association>
					</Association>
				</Association>
			</foreignAssociationInboundPath>

<!-- new CAE1.2 classes. -->

			<foreignAssociationInboundPath className="edu.pitt.cabig.cae.domain.general.ThreeDimensionalTumorSize"   cdeName="medicalRecordNumber" displaybleAttributes="greatestDimension,MVR" display="true">
				<Association className="edu.duke.catrip.cae.domain.general.ParticipantMedicalIdentifier">
					<Association className="edu.duke.catrip.cae.domain.general.Participant" roleName="participant">
						<Association className="edu.pitt.cabig.cae.domain.general.AnnotationEventParameters" roleName="annotationEventParametersCollection">
							<Association className="edu.pitt.cabig.cae.domain.general.ThreeDimensionalTumorSize" roleName="annotationSetCollection"/>
						</Association>
					</Association>
				</Association>
			</foreignAssociationInboundPath>

			<foreignAssociationInboundPath className="edu.pitt.cabig.cae.domain.breast.BreastSpecimenCharacteristics"   cdeName="medicalRecordNumber" displaybleAttributes="lymphNodeSamplingProcedure,laterality,lateralityMVR" display="true">
				<Association className="edu.duke.catrip.cae.domain.general.ParticipantMedicalIdentifier">
					<Association className="edu.duke.catrip.cae.domain.general.Participant" roleName="participant">
						<Association className="edu.pitt.cabig.cae.domain.general.AnnotationEventParameters" roleName="annotationEventParametersCollection">
							<Association className="edu.pitt.cabig.cae.domain.breast.BreastSpecimenCharacteristics" roleName="annotationSetCollection"/>
						</Association>
					</Association>
				</Association>
			</foreignAssociationInboundPath>

			<foreignAssociationInboundPath className="edu.pitt.cabig.cae.domain.breast.BreastCancerBiomarkers"   cdeName="medicalRecordNumber" displaybleAttributes="estrogenReceptor,progesteroneReceptor,HER2Status,HER2TestType,EGFRStatus" display="true">
				<Association className="edu.duke.catrip.cae.domain.general.ParticipantMedicalIdentifier">
					<Association className="edu.duke.catrip.cae.domain.general.Participant" roleName="participant">
						<Association className="edu.pitt.cabig.cae.domain.general.AnnotationEventParameters" roleName="annotationEventParametersCollection">
							<Association className="edu.pitt.cabig.cae.domain.breast.BreastCancerBiomarkers" roleName="annotationSetCollection"/>
						</Association>
					</Association>
				</Association>
			</foreignAssociationInboundPath>

<!-- new CAE1.2 classes. -->

		</foreignAssociationInboundTree>
	</service>
</simpleGuiServices>
