=== NCIP/catrip/catrip/codebase/projects/queryengine/schema/DCQL_schema_modified.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2006 rel. 3 sp1 (http://www.altova.com) by Srinivasa Akkala (Agile) -->
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:dcql="http://nci.nih.gov/cagrid/DCQL" xmlns:cql="http://CQL.caBIG/1/gov.nih.nci.cagrid.CQLQuery" targetNamespace="http://nci.nih.gov/cagrid/DCQL" elementFormDefault="qualified">
	<xsd:import namespace="http://CQL.caBIG/1/gov.nih.nci.cagrid.CQLQuery" schemaLocation="1_gov.nih.nci.cagrid.CQLQuery.xsd"/>
	<xsd:complexType name="Object">
		<xsd:annotation>
			<xsd:documentation>Associated Obects used as search criteria</xsd:documentation>
		</xsd:annotation>
		<xsd:choice>
			<xsd:element name="Attribute" type="cql:Attribute"/>
			<xsd:element name="Association" type="dcql:Association"/>
			<xsd:element name="ForeignAssociation" type="dcql:ForeignAssociation" minOccurs="0"/>
			<xsd:element name="Group" type="dcql:Group"/>
		</xsd:choice>
		<xsd:attribute name="name" type="xsd:string" use="required"/>
	</xsd:complexType>
	<xsd:complexType name="ForeignAssociation">
		<xsd:annotation>
			<xsd:documentation>Foreign Association in an external service</xsd:documentation>
		</xsd:annotation>
		<xsd:sequence>
			<xsd:element name="JoinCondition" type="dcql:JoinCondition"/>
			<xsd:element name="ForeignObject" type="dcql:Object"/>
		</xsd:sequence>
		<xsd:attribute name="roleName" type="xsd:string" use="optional"/>
		<xsd:attribute name="serviceURL" type="xsd:string" use="required"/>
	</xsd:complexType>
	<xsd:complexType name="JoinCondition">
		<xsd:annotation>
			<xsd:documentation>>Join condition specifies join to foreign association</xsd:documentation>
		</xsd:annotation>
		<xsd:sequence>
			<xsd:element name="LeftJoin" type="dcql:Join"/>
			<xsd:element name="RightJoin" type="dcql:Join"/>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="Join">
		<xsd:annotation>
			<xsd:documentation>Join type</xsd:documentation>
		</xsd:annotation>
		<xsd:sequence>
			<xsd:element name="Object" type="xsd:string"/>
			<xsd:element name="Attribute" type="xsd:string"/>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="Association">
		<xsd:annotation>
			<xsd:documentation>Object Association</xsd:documentation>
		</xsd:annotation>
		<xsd:sequence>
			<xsd:element name="Object" type="dcql:Object"/>
		</xsd:sequence>
		<xsd:attribute name="roleName" type="xsd:string" use="optional"/>
	</xsd:complexType>
	<xsd:complexType name="Group">
		<xsd:annotation>
			<xsd:documentation>Binary joint of two conditions</xsd:documentation>
		</xsd:annotation>
		<xsd:choice minOccurs="2" maxOccurs="unbounded">
			<xsd:element name="Association" type="dcql:Association"/>
			<xsd:element name="ForeignAssociation" type="dcql:ForeignAssociation"/>
			<xsd:element name="Attribute" type="cql:Attribute"/>
			<xsd:element name="Group" type="dcql:Group"/>
		</xsd:choice>
		<xsd:attribute name="logicRelation" type="cql:LogicalOperator" use="required"/>
	</xsd:complexType>
	<xsd:element name="FederatedQueryPlan">
		<xsd:annotation>
			<xsd:documentation>caGrid Federated Query Plan</xsd:documentation>
		</xsd:annotation>
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="TargetObject" type="dcql:Object"/>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
</xsd:schema>

=== NCIP/catrip/catrip/codebase/projects/queryengine/schema/SampleFederatedQry1.xml
<?xml version="1.0" encoding="UTF-8"?>
<FederatedQueryPlan xmlns="http://nci.nih.gov/cagrid/DCQL" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://nci.nih.gov/cagrid/DCQL
C:\Development\FederatedQueryEngine\schema1\DCQL_schema_modified.xsd">
	<TargetObject name="gov.nih.nci.ctom.domain.Patricipant">
		
		<Group logicRelation="AND">		
				<Group logicRelation="AND">
					<Attribute value="50" name="age" predicate="GREATER_THAN"></Attribute>
					<Attribute value="60" name="age" predicate="LESS_THAN"></Attribute>
				</Group>	
				<Group logicRelation="AND">

							
							<ForeignAssociation serviceURL="http://ctom">							
							<JoinCondition>
								<LeftJoin>
									<Object>gov.nih.nci.ctom.domain.Patricipant</Object>
									<Attribute>participantIdentifier</Attribute>
								</LeftJoin>
								<RightJoin>
									<Object>edu.pitt.cabig.cae.domain.general.Participant</Object>
									<Attribute>uniquePatientIdentifier</Attribute>
								</RightJoin>
							</JoinCondition>
							
							<ForeignObject name="edu.pitt.cabig.cae.domain.general.Patricipant" >	
									<Group logicRelation="AND">
										<Attribute value="AS%" name="middleName" predicate="LIKE"></Attribute>
										<Association roleName="annotationEventParameters">									
											<Object name="edu.pitt.cabig.cae.domain.general.AnnotationEventParameters">
												<Association roleName="annotationSetCollection">
													<Object name="edu.pitt.cabig.cae.domain.breast.NottinghamHistopathologicGrade">												
														<Group logicRelation="OR">
															<Attribute value="100" name="nuclearPleomorphism" predicate="EQUAL_TO"></Attribute>					
															<Group logicRelation="AND">
																<Attribute value="100" name="totalScore" predicate="GREATER_THAN"></Attribute>
																<Attribute value="60" name="mitoticCount" predicate="LESS_THAN"></Attribute>												
															</Group>	
														</Group>										
													</Object>										
												</Association>
											</Object>
										</Association>	
									</Group>																	
							</ForeignObject>						
						</ForeignAssociation>	

<!-- SERVICE # 2 -->
							<ForeignAssociation serviceURL="http://caTissue">
								<JoinCondition>
									<LeftJoin>
										<Object>gov.nih.nci.ctom.domain.Patricipant</Object>
										<Attribute>participantIdentifier</Attribute>
									</LeftJoin>
									<RightJoin>
										<Object>edu.pitt.cabig.catissue.Participant</Object>
										<Attribute>pi</Attribute>
									</RightJoin>
								</JoinCondition>
								<ForeignObject name="edu.pitt.cabig.catissue.Participant">
									<Attribute value="100" name="count" predicate="LESS_THAN"></Attribute>
								</ForeignObject>
							</ForeignAssociation>
				</Group>
		</Group>
	<!--
		<Association roleName="annotatableEntity">									
				<Object name="edu.pitt.cabig.cae.domain.general.AnnotationEventParameters">
					<Association roleName="annotationEventParameters">											
						<Object name="edu.pitt.cabig.cae.domain.breast.NottinghamHistopathologicGrade">			
								
								<Attribute value="100" name="totalScore" predicate="GREATER_THAN"></Attribute>
						</Object>
					</Association>
					
				</Object>
			</Association>					
-	
	<ForeignAssociation roleName="participantScore">
					    		
									<JoinCondition>
										<LeftJoin>
											<Object></Object>
											<Attribute></Attribute>
										</LeftJoin>
										<RightJoin>
											<Object></Object>
											<Attribute></Attribute>
										</RightJoin>
									</JoinCondition>
									
									<ForeignObject name="edu.pitt.cabig.cae.domain.general.Patricipant" >																	
											<Association roleName="annotatableEntity">																			
												<Object name="edu.pitt.cabig.cae.domain.general.AnnotationEventParameters">
													<Association roleName="annotationEventParameters">
														<Object name="edu.pitt.cabig.cae.domain.breast.NottinghamHistopathologicGrade">												
															<Attribute value="100" name="totalScore" predicate="GREATER_THAN"></Attribute>
														</Object>
													</Association>
												</Object>
											</Association>																		
									</ForeignObject>						
	</ForeignAssociation>	
	
		<Group logicRelation="AND">		
				<Attribute value="50" name="age" predicate="GREATER_THAN"></Attribute>
				<Attribute value="60" name="age" predicate="LESS_THAN"></Attribute>
				
				<Association roleName="caeParticipant">	
					
					<Object name="edu.pitt.cabig.cae.domain.general.Patricipant">
								
					    		<ForeignAssociation roleName="participantScore">
					    		
									<JoinCondition>
										<LeftJoin>
											<Object></Object>
											<Attribute></Attribute>
										</LeftJoin>
										<RightJoin>
											<Object></Object>
											<Attribute></Attribute>
										</RightJoin>
									</JoinCondition>
									
									<ForeignObject name="edu.pitt.cabig.cae.domain.general.Patricipant" >																	
											<Association roleName="annotatableEntity">									
												<Object name="edu.pitt.cabig.cae.domain.general.AnnotationEventParameters">
													<Association roleName="annotationEventParameters">
														<Object name="edu.pitt.cabig.cae.domain.breast.NottinghamHistopathologicGrade">												
															<Attribute value="100" name="totalScore" predicate="GREATER_THAN"></Attribute>
														</Object>
													</Association>
												</Object>
											</Association>																		
									</ForeignObject>						
								</ForeignAssociation>	
					</Object>
				</Association>
		</Group>
		-->
		
						
	</TargetObject>
</FederatedQueryPlan>
